### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by TomTasche** [huzongyao/AndroidMagic#2]
minSdkVersion is currently set to 15, but the NDK build platform used is 21. From my testing so far, this causes the library to crash on older devices.

> dlopen failed: cannot locate symbol "strtof" referenced by "libmagic.so"

**Comment by huzongyao** [comment]
fixed and I think it will work now, please try again.
the crash is caused by some missing functions of the old android sdk

**Comment by TomTasche** [comment]
seems to work fine now, thank you very much!
