### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [huzongyao/AndroidMagic#9]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by DJCrashdummy** [comment]
somehow i can't find this app in the official fdroid repo (not even in the archive)...?

**Comment by mondlicht-und-sterne** [comment]
@DJCrashdummy 

Not anymore, but it used to be.
